# permissions to do viewer testworkflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testworkflow-viewer-role
rules:
- apiGroups:
  - testworkflowframwork.example.com
  resources:
  - testworkflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testworkflowframwork.example.com
  resources:
  - testworkflows/status
  verbs:
  - get
